# Generated by Django 5.1 on 2024-09-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0006_doctorhospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(max_length=50)),
                ('learning_rate', models.FloatField(blank=True, null=True)),
                ('iterations', models.IntegerField(blank=True, null=True)),
                ('max_depth', models.IntegerField(blank=True, null=True)),
                ('n_estimators', models.IntegerField(blank=True, null=True)),
                ('accuracy', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
       
    ]
