# Generated by Django 5.1 on 2024-09-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0007_trainedmodel_heartdata_binarytree_and_more'),
    ]

    operations = [   
        migrations.AddField(
            model_name='heartdata',
            name='linearRegression',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
